### PR TITLE
Fix link field / typed link

### PR DESCRIPTION
**Pull request by timkelty**
### Description
The 2.0 release of https://github.com/sebastian-lenz/craft-linkfield changes it's name to "Link Field" as well as it's namespace.

### Related issues
https://github.com/sebastian-lenz/craft-linkfield/issues/122

### CODE REVIEW

**Comment by angrybrad** [comment]
@timkelty This would break anyone who updated to the latest version of FeedMe, but was still using the older 1.x versions of LinkField, no? Thinking the better option would be to add this was as a LinkField v2 and rename the old one to LinkField v1?

**Comment by timkelty** [comment]
@angrybrad yep I think you're right…that said I think since, Sebastian has add a proxy class: https://github.com/sebastian-lenz/craft-linkfield/blob/master/legacy/fields/LinkField.php, so it actually might just work now.

but real-talk…it seems like keeping third party integrations in here is always going to fragile in this regard. Personally I'd much rather see them yanked and PRs sent to the handful of plugins to implement (and further maintain) on the plugin side.

**Comment by angrybrad** [comment]
> but real-talk…it seems like keeping third party integrations in here is always going to fragile in this regard. Personally I'd much rather see them yanked and PRs sent to the handful of plugins to implement (and further maintain) on the plugin side.

Real talk, that is 100% the plan.

**Comment by sebastian-lenz** [comment]
I've added the FeedMe support directly to the plugin, so there should be no need for FeedMe to any changes.

**Pull request closed without merging**
