### PR TITLE
Fixed compatibility with Google Maps plugin v4.3+

### PR DESCRIPTION
**Pull request by lindseydiloreto**
### Description

Patches a compatibility issue with the Google Maps plugin (if using GM v4.3+).

> NOTE: If patching an existing feed, it may be necessary to **remap the Address subfields**.

### Related issues

https://github.com/doublesecretagency/craft-googlemaps/issues/78

### CODE REVIEW

**Comment by zizther** [comment]
I can confirm this PR fixes the issue with GM 4.3+
I had to remap the fields after updating.

Would be great to get this into Feed Me to support the latest versions of the Google Maps plugin

**Comment by lindseydiloreto** [comment]
@zizther Excellent, thank you for confirming! 👍

**Comment by angrybrad** [comment]
Thanks!

**Comment by lindseydiloreto** [comment]
Excellent, thanks @angrybrad! 🍺

**Comment by brandonkelly** [comment]
Feed Me 5.1.0 has been released with this change.

**Comment by lindseydiloreto** [comment]
Fantastic, thanks @brandonkelly! 🍺

**Pull request merged**
