### PR TITLE
Added check for simple arrays for newValues within existingValues

### PR DESCRIPTION
**Pull request by JeffreyBenusa**
### Description

For arrays - checking if the new array already existing and matches values in existing array.
Side conversation with @lindseydiloreto

### CODE REVIEW

**Comment by lindseydiloreto** [comment]
For clarity, this is to improve compatibility between Feed Me and the Google Maps plugin.

@JeffreyBenusa is importing data which includes Address data. The initial import is working fine. However, follow-up imports will attempt to re-import the _same Address data_, because it's not being recognized as existing data.

The patch that @JeffreyBenusa submitted should now recognize existing Address data, and not re-import that data.

**Comment by angrybrad** [comment]
Will be in the next release... thanks!

**Comment by lindseydiloreto** [comment]
Brilliant, thanks @angrybrad! 🍺

**Comment by ConversioniaDev** [comment]
Huzzah! Thanks @angrybrad.

**Pull request merged**
