### PR TITLE
Preventing array_merge_recursive with null value with super table, resolving #1364

### LINKED ISSUE #1364: array_merge_recursive error when no relations are found with super table
### Description
This issue corresponds with #1070. Which relates to the import of Matrix fields. The same issue occurs when importing items with the super table. I'll be making a PR to resolve this issue.

### Related issues
#1069 
#1070

### Additional info
- CraftCMS: 4.4.14
- Feedme: 5.2.0

### PR DESCRIPTION
**Pull request by jeffreyzant**
### Description
This fixes #1364 in the same way #1070 did.

### CODE REVIEW

**Comment by Humbi1992** [comment]
It should be fixed here to:

**vendor/craftcms/feed-me/src/fields/SuperTable.php : Line 125**
`$fieldData[$key]` = is_array($parsedValue) ? array_merge_recursive($fieldData[$key], $parsedValue) : $fieldData[$key];

**Review by Humbi1992 — CHANGES_REQUESTED** [review]
Fix it for matrix here too:
vendor/craftcms/feed-me/src/fields/SuperTable.php : Line 125

**Comment by jeffreyzant** [comment]
Hi @Humbi1992, I did not change that it because it would defer from the logic build in https://github.com/craftcms/feed-me/blob/develop/src/fields/Matrix.php#L130

Should I change that line aswell?

**Comment by Humbi1992** [comment]
@jeffreyzant Uhh i think I'm the wrong person to ask this :) but it fixed my error with a matrix field. So I thought it could be useful.

**Pull request merged**
